/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Sanaap API Documentation
 * Sanaap API documentation
 * OpenAPI spec version: 1.0
 */

export type ModelCreateOtpRequest = {
  phone_number: string;
}; 